name: build-solc

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake build-essential cvc4 wget libc6-dev libclang-dev pkg-config unzip
          {{if .Gcc7}}
          sudo apt-get install -y libboost1.67-all-dev gcc-7 g++-7
          {{else}}
          sudo apt-get install -y libboost-all-dev gcc-8 g++-8 gcc g++
          {{end}}
      # - name: Install z3
      #   run: |
      #     wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.17/z3-4.8.17-x64-glibc-2.31.zip
      #     unzip z3-4.8.17-x64-glibc-2.31.zip
      #     sudo cp z3-4.8.17-x64-glibc-2.31/include/* /usr/include/
      #     sudo cp z3-4.8.17-x64-glibc-2.31/bin/z3 /usr/bin/
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ethereum/solidity
          ref: {{.CommitHash}}
      - name: Build
        run: |
          mkdir build
          cd build
          
          {{if .Release}}
          touch ../prerelease.txt
          {{end}}

          {{if .Gcc7}}
          CC="gcc-7" CXX="g++-7" cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF -DUSE_CVC4=OFF
          CC="gcc-7" CXX="g++-7" make -j2
          {{else if .Gcc8}}
          CC="gcc-8" CXX="g++-8" cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF -DUSE_CVC4=OFF
          CC="gcc-8" CXX="g++-8" make -j2
          {{else}}
          cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF -DUSE_CVC4=OFF
          make -j2
          {{end}}
      - name: Hash
        run: |
          md5sum -b build/solc/solc | cut -d " " -f1 > md5.hash
          sha256sum -b build/solc/solc | cut -d " " -f1 > sha256.hash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: {{.TagName}}
          files: |
            build/solc/solc
            md5.hash
            sha256.hash
