name: build-vyper-list

on:
  push:
  schedule:
    # every day at midnight
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget jq findutils coreutils sed

      - name: Cache downloads
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: vyper-bin
          key: ${{ runner.os }}-vyper-bin

      - name: Build vyper list
        run: ./vyper_fetch.sh vyper.list.json

      - name: GIT commit and push all changed files
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git pull
          git add vyper.list.json
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
